package utils;

public enum TileType {
	CASTLE_ON_MOUNTAIN,
	MOUNTAIN_BASE,
	BETWEEN_TWO_MOUNTAIN,
	CURVE_OF_DEATH,
	DEEP_ABYSS,
	CASTLE_ON_ABYSS,
	WATERFALL_TO_ABYSS,
	STRAIGHT_RIVER,
	CURVE_RIVER,
	STRAIGHT_RIVER_BESIDE_ABYSS,
	CURVE_RIVER_TURN_LEFT_AT_ABYSS,
	CURVE_RIVER_TURN_RIGHT_AT_ABYSS,
	CURVE_RIVER_BESIDE_ABYSS,
	TJUNCTION_RIVER,
	TJUNCTION_RIVER_BESIDE_ABYSS,
	CROSSROAD_RIVER,
	EMPTY
}
